gmake -j16 cipulot/2key:via
gmake -j16 cipulot/60xt:via
gmake -j16 cipulot/alpha_omega_ec_60:via
gmake -j16 cipulot/babykeeb:via
gmake -j16 cipulot/chroma:via
gmake -j16 cipulot/des_60:via
gmake -j16 cipulot/ec_23u:via
gmake -j16 cipulot/ec_60:via
gmake -j16 cipulot/ec_60x:via
gmake -j16 cipulot/ec_660c:via
gmake -j16 cipulot/ec_980c:via
gmake -j16 cipulot/ec_adore_75:via
gmake -j16 cipulot/ec_alveus/1_0_0:via
gmake -j16 cipulot/ec_alveus/1_2_0:via
gmake -j16 cipulot/ec_dafu:via
gmake -j16 cipulot/ec_dolice:via
gmake -j16 cipulot/ec_menhir:via
gmake -j16 cipulot/ec_pro2:via
gmake -j16 cipulot/ec_prox/ansi_iso:via
gmake -j16 cipulot/ec_prox/jis:via
gmake -j16 cipulot/ec_theca:via
gmake -j16 cipulot/ec_tkl:via
gmake -j16 cipulot/ec_tkl_proto:via
gmake -j16 cipulot/ec_typeb:via
gmake -j16 cipulot/ec_typek:via
gmake -j16 cipulot/ec_vero:via
gmake -j16 cipulot/ec_virgo:via
gmake -j16 cipulot/he_60:via
gmake -j16 cipulot/je_bae_ted/mx_je_bae_ted:via
gmake -j16 cipulot/je_bae_ted/ec_je_bae_ted:via
gmake -j16 cipulot/lilium:via
gmake -j16 cipulot/mnk_60_ec:via
gmake -j16 cipulot/mnk_65_ec:via
gmake -j16 cipulot/raita_ec:via
gmake -j16 cipulot/rf_r1_8_9xu:via
gmake -j16 cipulot/unrealforce:via
